### ISSUE TITLE
Publish Eduroam UU

### ISSUE THREAD

**Issue by ZJvandeWeg** [orschiro/orschiro-pkgbuilds.archived#3]
Probably lost during the migration to Aur 4.0. Though it seems the `netctl-eduroam-uu` is not in the AUR anymore. 

Also, it seems to depend on the `ppp` package in [core].

**Comment by orschiro** [comment]
@ZJvandeWeg 

Thanks for fileing this issue! I should probably somehow archive this repository as I am currently not using Arch (I switched to elementaryOS) and didn't migrate any package to AUR 4.0. 

Please feel free to fork this repository and re-upload the desired packages to the AUR.

**Comment by ZJvandeWeg** [comment]
As I only need the one, I wont fork it, just set up a new repo if you are fine with that. 
Ill put you there as maintainer, for your due credit. 

If you have any trouble with this, please contact me.

**Comment by orschiro** [comment]
Perfectly fine with me, thanks for your pro-activity!
